# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  hellworldservice:
    runs-on: ubuntu-latest
    steps:
      - name: Launch my service here
        run: echo "Service launched by GITHUB_REF"
        
  #  services:
  #    image: hello-world
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "who is pushing this code $GITHUB_ACTOR"
  greeting_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
          
    env:
      Greeting: Hello
      DAY_OF_WEEK: Tuesday

